build: off

clone_folder: c:\gopath\src\github.com\LaurenceCheng\testutils

environment:
  GOPATH: c:\gopath

stack: go 1.12

install:
  - go get -u -v github.com/jstemmer/go-junit-report

before_test:
  - go vet ./...

test_script:
  - go test ./... | c:\gopath\bin\go-junit-report > tests_report.xml

on_finish:
- ps: type (Resolve-Path .\tests_report.xml)
- ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests_report.xml))
